# =========================================================
# application.yml
# Base configuration. No profile activated by default.
# The correct profile is chosen via SPRING_PROFILES_ACTIVE or @ActiveProfiles in tests.
# =========================================================

server:
  port: ${SPRING_LOCAL_PORT:8080}

spring:
  application:
    name: news-platform

logging:
  level:
    root: INFO