# =========================================================
# application.yml
# Base configuration. No profile activated by default.
# The correct profile is chosen via SPRING_PROFILES_ACTIVE
# environment variable, command-line args, or @ActiveProfiles in tests.
# =========================================================

spring:
  application:
    name: news-platform

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.newsplatform: DEBUG