# =========================================================
# application.yml
# Base application configuration (fallback defaults).
# Used when no specific Spring profile is active.
# Should not contain any secrets; all passwords should come from ENV vars.
# =========================================================

server:
  port: ${SPRING_LOCAL_PORT:8080}   # Default server port if not overridden

spring:
  application:
    name: news-platform

  profiles:
    active: local  # Default profile for local development

logging:
  level:
    root: INFO