server:
  port: ${SPRING_LOCAL_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    com.example.newsplatform: DEBUG
    org.springframework.security: DEBUG
    org.springframework.jdbc.core: DEBUG