# =========================================================
# application-prod.yml
# Production configuration.
# All secrets (DB credentials, admin credentials) must be provided via .env / ENV vars.
# Schema changes are never allowed automatically in production.
# =========================================================

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

server:
  port: ${SPRING_LOCAL_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate   # Validate schema only, do not auto-update
    show-sql: false        # No SQL logs in production

logging:
  level:
    com.example.newsplatform: INFO
    org.springframework.security: WARN
    org.springframework.jdbc.core: ERROR