# =========================================================
# application-prod.yml
# Production profile.
# Injected from Render Secret File or ENV variables.
# Never commit real values into git.
# =========================================================

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: none        # Never auto-manage schema in prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

logging:
  level:
    root: ERROR